######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 21 15:18:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

OBJECTS_DIR = .obj
MOC_DIR = .moc
RCC_DIR = .rcc

# Input
HEADERS += MainWindow.H Universe.H
SOURCES += main.C MainWindow.C Universe.C
RESOURCES += unicode.qrc
